// Golden expected-forms fixture for the conjugator hardening harness (v0.6.4).
//
// PURPOSE: the admission rule for canDisplayParadigm is "fixture == conjugate() for the FULL
// paradigm". A verb may not enter TRUSTED_LEMMAS without a complete, correct entry here.
//
// INDEPENDENCE: these are the CORRECT RAE/reference forms, verified cell-by-cell by hand before
// freezing — not blindly copied from conjugate(). That independent review is what flagged the
// three blind spots EXCLUDED from this fixture (and from the trusted set):
//   • poder   → gerund "pudiendo" (engine emits regular "podiendo"; can't be fixed via WEAK_STEM
//               without breaking its regular subjunctive "podamos") — logged to backlog.
//   • creer   → preterite hiatus accents "creíste/creímos/creísteis" (engine drops them) — backlog.
//   • haber   → auxiliary; no learner imperative ("ha"/"habed" are nonsense) — backlog.
// HIGH-RISK cells (orthographic subjunctive/preterite + every irregular imperative) were the
// review focus: z→c (almorzar→almorcé/almuerce), c→qu (volcar→volqué/vuelque, jugar→jugué/juguemos),
// gu→g (seguir→sigo/siga/siguió), and the tú/usted/nosotros/vosotros affirmative imperatives of the
// 15 fully-irregular verbs (está/dé/sea/ten/vamos…). Regular cells are verified by the clean-room
// regularReference() in conjugator.test.ts, not listed here.

import type { Tense } from './conjugator'

export type ExpectedParadigm = {
  readonly [K in Exclude<Tense, 'infinitivo'>]: K extends 'gerundio' | 'participio'
    ? string
    : readonly (string | null)[]
}

// Keyed by infinitive (reflexive variants inherit via stripReflexive in canDisplayParadigm).
export const EXPECTED: Readonly<Record<string, ExpectedParadigm>> = {
  ser: {
    presente: ['soy', 'eres', 'es', 'somos', 'sois', 'son'],
    preterito: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
    imperfecto: ['era', 'eras', 'era', 'éramos', 'erais', 'eran'],
    futuro: ['seré', 'serás', 'será', 'seremos', 'seréis', 'serán'],
    condicional: ['sería', 'serías', 'sería', 'seríamos', 'seríais', 'serían'],
    subjPresente: ['sea', 'seas', 'sea', 'seamos', 'seáis', 'sean'],
    imperativoAfirmativo: [null, 'sé', 'sea', 'seamos', 'sed', 'sean'],
    imperativoNegativo: [null, 'no seas', 'no sea', 'no seamos', 'no seáis', 'no sean'],
    gerundio: 'siendo', participio: 'sido',
  },
  ir: {
    presente: ['voy', 'vas', 'va', 'vamos', 'vais', 'van'],
    preterito: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
    imperfecto: ['iba', 'ibas', 'iba', 'íbamos', 'ibais', 'iban'],
    futuro: ['iré', 'irás', 'irá', 'iremos', 'iréis', 'irán'],
    condicional: ['iría', 'irías', 'iría', 'iríamos', 'iríais', 'irían'],
    subjPresente: ['vaya', 'vayas', 'vaya', 'vayamos', 'vayáis', 'vayan'],
    imperativoAfirmativo: [null, 've', 'vaya', 'vamos', 'id', 'vayan'],
    imperativoNegativo: [null, 'no vayas', 'no vaya', 'no vayamos', 'no vayáis', 'no vayan'],
    gerundio: 'yendo', participio: 'ido',
  },
  ver: {
    presente: ['veo', 'ves', 've', 'vemos', 'veis', 'ven'],
    preterito: ['vi', 'viste', 'vio', 'vimos', 'visteis', 'vieron'],
    imperfecto: ['veía', 'veías', 'veía', 'veíamos', 'veíais', 'veían'],
    futuro: ['veré', 'verás', 'verá', 'veremos', 'veréis', 'verán'],
    condicional: ['vería', 'verías', 'vería', 'veríamos', 'veríais', 'verían'],
    subjPresente: ['vea', 'veas', 'vea', 'veamos', 'veáis', 'vean'],
    imperativoAfirmativo: [null, 've', 'vea', 'veamos', 'ved', 'vean'],
    imperativoNegativo: [null, 'no veas', 'no vea', 'no veamos', 'no veáis', 'no vean'],
    gerundio: 'viendo', participio: 'visto',
  },
  estar: {
    presente: ['estoy', 'estás', 'está', 'estamos', 'estáis', 'están'],
    preterito: ['estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron'],
    imperfecto: ['estaba', 'estabas', 'estaba', 'estábamos', 'estabais', 'estaban'],
    futuro: ['estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán'],
    condicional: ['estaría', 'estarías', 'estaría', 'estaríamos', 'estaríais', 'estarían'],
    subjPresente: ['esté', 'estés', 'esté', 'estemos', 'estéis', 'estén'],
    imperativoAfirmativo: [null, 'está', 'esté', 'estemos', 'estad', 'estén'],
    imperativoNegativo: [null, 'no estés', 'no esté', 'no estemos', 'no estéis', 'no estén'],
    gerundio: 'estando', participio: 'estado',
  },
  dar: {
    presente: ['doy', 'das', 'da', 'damos', 'dais', 'dan'],
    preterito: ['di', 'diste', 'dio', 'dimos', 'disteis', 'dieron'],
    imperfecto: ['daba', 'dabas', 'daba', 'dábamos', 'dabais', 'daban'],
    futuro: ['daré', 'darás', 'dará', 'daremos', 'daréis', 'darán'],
    condicional: ['daría', 'darías', 'daría', 'daríamos', 'daríais', 'darían'],
    subjPresente: ['dé', 'des', 'dé', 'demos', 'deis', 'den'],
    imperativoAfirmativo: [null, 'da', 'dé', 'demos', 'dad', 'den'],
    imperativoNegativo: [null, 'no des', 'no dé', 'no demos', 'no deis', 'no den'],
    gerundio: 'dando', participio: 'dado',
  },
  hacer: {
    presente: ['hago', 'haces', 'hace', 'hacemos', 'hacéis', 'hacen'],
    preterito: ['hice', 'hiciste', 'hizo', 'hicimos', 'hicisteis', 'hicieron'],
    imperfecto: ['hacía', 'hacías', 'hacía', 'hacíamos', 'hacíais', 'hacían'],
    futuro: ['haré', 'harás', 'hará', 'haremos', 'haréis', 'harán'],
    condicional: ['haría', 'harías', 'haría', 'haríamos', 'haríais', 'harían'],
    subjPresente: ['haga', 'hagas', 'haga', 'hagamos', 'hagáis', 'hagan'],
    imperativoAfirmativo: [null, 'haz', 'haga', 'hagamos', 'haced', 'hagan'],
    imperativoNegativo: [null, 'no hagas', 'no haga', 'no hagamos', 'no hagáis', 'no hagan'],
    gerundio: 'haciendo', participio: 'hecho',
  },
  decir: {
    presente: ['digo', 'dices', 'dice', 'decimos', 'decís', 'dicen'],
    preterito: ['dije', 'dijiste', 'dijo', 'dijimos', 'dijisteis', 'dijeron'],
    imperfecto: ['decía', 'decías', 'decía', 'decíamos', 'decíais', 'decían'],
    futuro: ['diré', 'dirás', 'dirá', 'diremos', 'diréis', 'dirán'],
    condicional: ['diría', 'dirías', 'diría', 'diríamos', 'diríais', 'dirían'],
    subjPresente: ['diga', 'digas', 'diga', 'digamos', 'digáis', 'digan'],
    imperativoAfirmativo: [null, 'di', 'diga', 'digamos', 'decid', 'digan'],
    imperativoNegativo: [null, 'no digas', 'no diga', 'no digamos', 'no digáis', 'no digan'],
    gerundio: 'diciendo', participio: 'dicho',
  },
  tener: {
    presente: ['tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen'],
    preterito: ['tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron'],
    imperfecto: ['tenía', 'tenías', 'tenía', 'teníamos', 'teníais', 'tenían'],
    futuro: ['tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán'],
    condicional: ['tendría', 'tendrías', 'tendría', 'tendríamos', 'tendríais', 'tendrían'],
    subjPresente: ['tenga', 'tengas', 'tenga', 'tengamos', 'tengáis', 'tengan'],
    imperativoAfirmativo: [null, 'ten', 'tenga', 'tengamos', 'tened', 'tengan'],
    imperativoNegativo: [null, 'no tengas', 'no tenga', 'no tengamos', 'no tengáis', 'no tengan'],
    gerundio: 'teniendo', participio: 'tenido',
  },
  venir: {
    presente: ['vengo', 'vienes', 'viene', 'venimos', 'venís', 'vienen'],
    preterito: ['vine', 'viniste', 'vino', 'vinimos', 'vinisteis', 'vinieron'],
    imperfecto: ['venía', 'venías', 'venía', 'veníamos', 'veníais', 'venían'],
    futuro: ['vendré', 'vendrás', 'vendrá', 'vendremos', 'vendréis', 'vendrán'],
    condicional: ['vendría', 'vendrías', 'vendría', 'vendríamos', 'vendríais', 'vendrían'],
    subjPresente: ['venga', 'vengas', 'venga', 'vengamos', 'vengáis', 'vengan'],
    imperativoAfirmativo: [null, 'ven', 'venga', 'vengamos', 'venid', 'vengan'],
    imperativoNegativo: [null, 'no vengas', 'no venga', 'no vengamos', 'no vengáis', 'no vengan'],
    gerundio: 'viniendo', participio: 'venido',
  },
  poner: {
    presente: ['pongo', 'pones', 'pone', 'ponemos', 'ponéis', 'ponen'],
    preterito: ['puse', 'pusiste', 'puso', 'pusimos', 'pusisteis', 'pusieron'],
    imperfecto: ['ponía', 'ponías', 'ponía', 'poníamos', 'poníais', 'ponían'],
    futuro: ['pondré', 'pondrás', 'pondrá', 'pondremos', 'pondréis', 'pondrán'],
    condicional: ['pondría', 'pondrías', 'pondría', 'pondríamos', 'pondríais', 'pondrían'],
    subjPresente: ['ponga', 'pongas', 'ponga', 'pongamos', 'pongáis', 'pongan'],
    imperativoAfirmativo: [null, 'pon', 'ponga', 'pongamos', 'poned', 'pongan'],
    imperativoNegativo: [null, 'no pongas', 'no ponga', 'no pongamos', 'no pongáis', 'no pongan'],
    gerundio: 'poniendo', participio: 'puesto',
  },
  salir: {
    presente: ['salgo', 'sales', 'sale', 'salimos', 'salís', 'salen'],
    preterito: ['salí', 'saliste', 'salió', 'salimos', 'salisteis', 'salieron'],
    imperfecto: ['salía', 'salías', 'salía', 'salíamos', 'salíais', 'salían'],
    futuro: ['saldré', 'saldrás', 'saldrá', 'saldremos', 'saldréis', 'saldrán'],
    condicional: ['saldría', 'saldrías', 'saldría', 'saldríamos', 'saldríais', 'saldrían'],
    subjPresente: ['salga', 'salgas', 'salga', 'salgamos', 'salgáis', 'salgan'],
    imperativoAfirmativo: [null, 'sal', 'salga', 'salgamos', 'salid', 'salgan'],
    imperativoNegativo: [null, 'no salgas', 'no salga', 'no salgamos', 'no salgáis', 'no salgan'],
    gerundio: 'saliendo', participio: 'salido',
  },
  saber: {
    presente: ['sé', 'sabes', 'sabe', 'sabemos', 'sabéis', 'saben'],
    preterito: ['supe', 'supiste', 'supo', 'supimos', 'supisteis', 'supieron'],
    imperfecto: ['sabía', 'sabías', 'sabía', 'sabíamos', 'sabíais', 'sabían'],
    futuro: ['sabré', 'sabrás', 'sabrá', 'sabremos', 'sabréis', 'sabrán'],
    condicional: ['sabría', 'sabrías', 'sabría', 'sabríamos', 'sabríais', 'sabrían'],
    subjPresente: ['sepa', 'sepas', 'sepa', 'sepamos', 'sepáis', 'sepan'],
    imperativoAfirmativo: [null, 'sabe', 'sepa', 'sepamos', 'sabed', 'sepan'],
    imperativoNegativo: [null, 'no sepas', 'no sepa', 'no sepamos', 'no sepáis', 'no sepan'],
    gerundio: 'sabiendo', participio: 'sabido',
  },
  traer: {
    presente: ['traigo', 'traes', 'trae', 'traemos', 'traéis', 'traen'],
    preterito: ['traje', 'trajiste', 'trajo', 'trajimos', 'trajisteis', 'trajeron'],
    imperfecto: ['traía', 'traías', 'traía', 'traíamos', 'traíais', 'traían'],
    futuro: ['traeré', 'traerás', 'traerá', 'traeremos', 'traeréis', 'traerán'],
    condicional: ['traería', 'traerías', 'traería', 'traeríamos', 'traeríais', 'traerían'],
    subjPresente: ['traiga', 'traigas', 'traiga', 'traigamos', 'traigáis', 'traigan'],
    imperativoAfirmativo: [null, 'trae', 'traiga', 'traigamos', 'traed', 'traigan'],
    imperativoNegativo: [null, 'no traigas', 'no traiga', 'no traigamos', 'no traigáis', 'no traigan'],
    gerundio: 'trayendo', participio: 'traído',
  },
  extraer: {
    presente: ['extraigo', 'extraes', 'extrae', 'extraemos', 'extraéis', 'extraen'],
    preterito: ['extraje', 'extrajiste', 'extrajo', 'extrajimos', 'extrajisteis', 'extrajeron'],
    imperfecto: ['extraía', 'extraías', 'extraía', 'extraíamos', 'extraíais', 'extraían'],
    futuro: ['extraeré', 'extraerás', 'extraerá', 'extraeremos', 'extraeréis', 'extraerán'],
    condicional: ['extraería', 'extraerías', 'extraería', 'extraeríamos', 'extraeríais', 'extraerían'],
    subjPresente: ['extraiga', 'extraigas', 'extraiga', 'extraigamos', 'extraigáis', 'extraigan'],
    imperativoAfirmativo: [null, 'extrae', 'extraiga', 'extraigamos', 'extraed', 'extraigan'],
    imperativoNegativo: [null, 'no extraigas', 'no extraiga', 'no extraigamos', 'no extraigáis', 'no extraigan'],
    gerundio: 'extrayendo', participio: 'extraído',
  },
  conducir: {
    presente: ['conduzco', 'conduces', 'conduce', 'conducimos', 'conducís', 'conducen'],
    preterito: ['conduje', 'condujiste', 'condujo', 'condujimos', 'condujisteis', 'condujeron'],
    imperfecto: ['conducía', 'conducías', 'conducía', 'conducíamos', 'conducíais', 'conducían'],
    futuro: ['conduciré', 'conducirás', 'conducirá', 'conduciremos', 'conduciréis', 'conducirán'],
    condicional: ['conduciría', 'conducirías', 'conduciría', 'conduciríamos', 'conduciríais', 'conducirían'],
    subjPresente: ['conduzca', 'conduzcas', 'conduzca', 'conduzcamos', 'conduzcáis', 'conduzcan'],
    imperativoAfirmativo: [null, 'conduce', 'conduzca', 'conduzcamos', 'conducid', 'conduzcan'],
    imperativoNegativo: [null, 'no conduzcas', 'no conduzca', 'no conduzcamos', 'no conduzcáis', 'no conduzcan'],
    gerundio: 'conduciendo', participio: 'conducido',
  },
  pensar: {
    presente: ['pienso', 'piensas', 'piensa', 'pensamos', 'pensáis', 'piensan'],
    preterito: ['pensé', 'pensaste', 'pensó', 'pensamos', 'pensasteis', 'pensaron'],
    imperfecto: ['pensaba', 'pensabas', 'pensaba', 'pensábamos', 'pensabais', 'pensaban'],
    futuro: ['pensaré', 'pensarás', 'pensará', 'pensaremos', 'pensaréis', 'pensarán'],
    condicional: ['pensaría', 'pensarías', 'pensaría', 'pensaríamos', 'pensaríais', 'pensarían'],
    subjPresente: ['piense', 'pienses', 'piense', 'pensemos', 'penséis', 'piensen'],
    imperativoAfirmativo: [null, 'piensa', 'piense', 'pensemos', 'pensad', 'piensen'],
    imperativoNegativo: [null, 'no pienses', 'no piense', 'no pensemos', 'no penséis', 'no piensen'],
    gerundio: 'pensando', participio: 'pensado',
  },
  cerrar: {
    presente: ['cierro', 'cierras', 'cierra', 'cerramos', 'cerráis', 'cierran'],
    preterito: ['cerré', 'cerraste', 'cerró', 'cerramos', 'cerrasteis', 'cerraron'],
    imperfecto: ['cerraba', 'cerrabas', 'cerraba', 'cerrábamos', 'cerrabais', 'cerraban'],
    futuro: ['cerraré', 'cerrarás', 'cerrará', 'cerraremos', 'cerraréis', 'cerrarán'],
    condicional: ['cerraría', 'cerrarías', 'cerraría', 'cerraríamos', 'cerraríais', 'cerrarían'],
    subjPresente: ['cierre', 'cierres', 'cierre', 'cerremos', 'cerréis', 'cierren'],
    imperativoAfirmativo: [null, 'cierra', 'cierre', 'cerremos', 'cerrad', 'cierren'],
    imperativoNegativo: [null, 'no cierres', 'no cierre', 'no cerremos', 'no cerréis', 'no cierren'],
    gerundio: 'cerrando', participio: 'cerrado',
  },
  comenzar: {
    presente: ['comienzo', 'comienzas', 'comienza', 'comenzamos', 'comenzáis', 'comienzan'],
    preterito: ['comencé', 'comenzaste', 'comenzó', 'comenzamos', 'comenzasteis', 'comenzaron'],
    imperfecto: ['comenzaba', 'comenzabas', 'comenzaba', 'comenzábamos', 'comenzabais', 'comenzaban'],
    futuro: ['comenzaré', 'comenzarás', 'comenzará', 'comenzaremos', 'comenzaréis', 'comenzarán'],
    condicional: ['comenzaría', 'comenzarías', 'comenzaría', 'comenzaríamos', 'comenzaríais', 'comenzarían'],
    subjPresente: ['comience', 'comiences', 'comience', 'comencemos', 'comencéis', 'comiencen'],
    imperativoAfirmativo: [null, 'comienza', 'comience', 'comencemos', 'comenzad', 'comiencen'],
    imperativoNegativo: [null, 'no comiences', 'no comience', 'no comencemos', 'no comencéis', 'no comiencen'],
    gerundio: 'comenzando', participio: 'comenzado',
  },
  empezar: {
    presente: ['empiezo', 'empiezas', 'empieza', 'empezamos', 'empezáis', 'empiezan'],
    preterito: ['empecé', 'empezaste', 'empezó', 'empezamos', 'empezasteis', 'empezaron'],
    imperfecto: ['empezaba', 'empezabas', 'empezaba', 'empezábamos', 'empezabais', 'empezaban'],
    futuro: ['empezaré', 'empezarás', 'empezará', 'empezaremos', 'empezaréis', 'empezarán'],
    condicional: ['empezaría', 'empezarías', 'empezaría', 'empezaríamos', 'empezaríais', 'empezarían'],
    subjPresente: ['empiece', 'empieces', 'empiece', 'empecemos', 'empecéis', 'empiecen'],
    imperativoAfirmativo: [null, 'empieza', 'empiece', 'empecemos', 'empezad', 'empiecen'],
    imperativoNegativo: [null, 'no empieces', 'no empiece', 'no empecemos', 'no empecéis', 'no empiecen'],
    gerundio: 'empezando', participio: 'empezado',
  },
  entender: {
    presente: ['entiendo', 'entiendes', 'entiende', 'entendemos', 'entendéis', 'entienden'],
    preterito: ['entendí', 'entendiste', 'entendió', 'entendimos', 'entendisteis', 'entendieron'],
    imperfecto: ['entendía', 'entendías', 'entendía', 'entendíamos', 'entendíais', 'entendían'],
    futuro: ['entenderé', 'entenderás', 'entenderá', 'entenderemos', 'entenderéis', 'entenderán'],
    condicional: ['entendería', 'entenderías', 'entendería', 'entenderíamos', 'entenderíais', 'entenderían'],
    subjPresente: ['entienda', 'entiendas', 'entienda', 'entendamos', 'entendáis', 'entiendan'],
    imperativoAfirmativo: [null, 'entiende', 'entienda', 'entendamos', 'entended', 'entiendan'],
    imperativoNegativo: [null, 'no entiendas', 'no entienda', 'no entendamos', 'no entendáis', 'no entiendan'],
    gerundio: 'entendiendo', participio: 'entendido',
  },
  perder: {
    presente: ['pierdo', 'pierdes', 'pierde', 'perdemos', 'perdéis', 'pierden'],
    preterito: ['perdí', 'perdiste', 'perdió', 'perdimos', 'perdisteis', 'perdieron'],
    imperfecto: ['perdía', 'perdías', 'perdía', 'perdíamos', 'perdíais', 'perdían'],
    futuro: ['perderé', 'perderás', 'perderá', 'perderemos', 'perderéis', 'perderán'],
    condicional: ['perdería', 'perderías', 'perdería', 'perderíamos', 'perderíais', 'perderían'],
    subjPresente: ['pierda', 'pierdas', 'pierda', 'perdamos', 'perdáis', 'pierdan'],
    imperativoAfirmativo: [null, 'pierde', 'pierda', 'perdamos', 'perded', 'pierdan'],
    imperativoNegativo: [null, 'no pierdas', 'no pierda', 'no perdamos', 'no perdáis', 'no pierdan'],
    gerundio: 'perdiendo', participio: 'perdido',
  },
  querer: {
    presente: ['quiero', 'quieres', 'quiere', 'queremos', 'queréis', 'quieren'],
    preterito: ['quise', 'quisiste', 'quiso', 'quisimos', 'quisisteis', 'quisieron'],
    imperfecto: ['quería', 'querías', 'quería', 'queríamos', 'queríais', 'querían'],
    futuro: ['querré', 'querrás', 'querrá', 'querremos', 'querréis', 'querrán'],
    condicional: ['querría', 'querrías', 'querría', 'querríamos', 'querríais', 'querrían'],
    subjPresente: ['quiera', 'quieras', 'quiera', 'queramos', 'queráis', 'quieran'],
    imperativoAfirmativo: [null, 'quiere', 'quiera', 'queramos', 'quered', 'quieran'],
    imperativoNegativo: [null, 'no quieras', 'no quiera', 'no queramos', 'no queráis', 'no quieran'],
    gerundio: 'queriendo', participio: 'querido',
  },
  sentir: {
    presente: ['siento', 'sientes', 'siente', 'sentimos', 'sentís', 'sienten'],
    preterito: ['sentí', 'sentiste', 'sintió', 'sentimos', 'sentisteis', 'sintieron'],
    imperfecto: ['sentía', 'sentías', 'sentía', 'sentíamos', 'sentíais', 'sentían'],
    futuro: ['sentiré', 'sentirás', 'sentirá', 'sentiremos', 'sentiréis', 'sentirán'],
    condicional: ['sentiría', 'sentirías', 'sentiría', 'sentiríamos', 'sentiríais', 'sentirían'],
    subjPresente: ['sienta', 'sientas', 'sienta', 'sintamos', 'sintáis', 'sientan'],
    imperativoAfirmativo: [null, 'siente', 'sienta', 'sintamos', 'sentid', 'sientan'],
    imperativoNegativo: [null, 'no sientas', 'no sienta', 'no sintamos', 'no sintáis', 'no sientan'],
    gerundio: 'sintiendo', participio: 'sentido',
  },
  divertir: {
    presente: ['divierto', 'diviertes', 'divierte', 'divertimos', 'divertís', 'divierten'],
    preterito: ['divertí', 'divertiste', 'divirtió', 'divertimos', 'divertisteis', 'divirtieron'],
    imperfecto: ['divertía', 'divertías', 'divertía', 'divertíamos', 'divertíais', 'divertían'],
    futuro: ['divertiré', 'divertirás', 'divertirá', 'divertiremos', 'divertiréis', 'divertirán'],
    condicional: ['divertiría', 'divertirías', 'divertiría', 'divertiríamos', 'divertiríais', 'divertirían'],
    subjPresente: ['divierta', 'diviertas', 'divierta', 'divirtamos', 'divirtáis', 'diviertan'],
    imperativoAfirmativo: [null, 'divierte', 'divierta', 'divirtamos', 'divertid', 'diviertan'],
    imperativoNegativo: [null, 'no diviertas', 'no divierta', 'no divirtamos', 'no divirtáis', 'no diviertan'],
    gerundio: 'divirtiendo', participio: 'divertido',
  },
  hervir: {
    presente: ['hiervo', 'hierves', 'hierve', 'hervimos', 'hervís', 'hierven'],
    preterito: ['herví', 'herviste', 'hirvió', 'hervimos', 'hervisteis', 'hirvieron'],
    imperfecto: ['hervía', 'hervías', 'hervía', 'hervíamos', 'hervíais', 'hervían'],
    futuro: ['herviré', 'hervirás', 'hervirá', 'herviremos', 'herviréis', 'hervirán'],
    condicional: ['herviría', 'hervirías', 'herviría', 'herviríamos', 'herviríais', 'hervirían'],
    subjPresente: ['hierva', 'hiervas', 'hierva', 'hirvamos', 'hirváis', 'hiervan'],
    imperativoAfirmativo: [null, 'hierve', 'hierva', 'hirvamos', 'hervid', 'hiervan'],
    imperativoNegativo: [null, 'no hiervas', 'no hierva', 'no hirvamos', 'no hirváis', 'no hiervan'],
    gerundio: 'hirviendo', participio: 'hervido',
  },
  preferir: {
    presente: ['prefiero', 'prefieres', 'prefiere', 'preferimos', 'preferís', 'prefieren'],
    preterito: ['preferí', 'preferiste', 'prefirió', 'preferimos', 'preferisteis', 'prefirieron'],
    imperfecto: ['prefería', 'preferías', 'prefería', 'preferíamos', 'preferíais', 'preferían'],
    futuro: ['preferiré', 'preferirás', 'preferirá', 'preferiremos', 'preferiréis', 'preferirán'],
    condicional: ['preferiría', 'preferirías', 'preferiría', 'preferiríamos', 'preferiríais', 'preferirían'],
    subjPresente: ['prefiera', 'prefieras', 'prefiera', 'prefiramos', 'prefiráis', 'prefieran'],
    imperativoAfirmativo: [null, 'prefiere', 'prefiera', 'prefiramos', 'preferid', 'prefieran'],
    imperativoNegativo: [null, 'no prefieras', 'no prefiera', 'no prefiramos', 'no prefiráis', 'no prefieran'],
    gerundio: 'prefiriendo', participio: 'preferido',
  },
  volver: {
    presente: ['vuelvo', 'vuelves', 'vuelve', 'volvemos', 'volvéis', 'vuelven'],
    preterito: ['volví', 'volviste', 'volvió', 'volvimos', 'volvisteis', 'volvieron'],
    imperfecto: ['volvía', 'volvías', 'volvía', 'volvíamos', 'volvíais', 'volvían'],
    futuro: ['volveré', 'volverás', 'volverá', 'volveremos', 'volveréis', 'volverán'],
    condicional: ['volvería', 'volverías', 'volvería', 'volveríamos', 'volveríais', 'volverían'],
    subjPresente: ['vuelva', 'vuelvas', 'vuelva', 'volvamos', 'volváis', 'vuelvan'],
    imperativoAfirmativo: [null, 'vuelve', 'vuelva', 'volvamos', 'volved', 'vuelvan'],
    imperativoNegativo: [null, 'no vuelvas', 'no vuelva', 'no volvamos', 'no volváis', 'no vuelvan'],
    gerundio: 'volviendo', participio: 'vuelto',
  },
  contar: {
    presente: ['cuento', 'cuentas', 'cuenta', 'contamos', 'contáis', 'cuentan'],
    preterito: ['conté', 'contaste', 'contó', 'contamos', 'contasteis', 'contaron'],
    imperfecto: ['contaba', 'contabas', 'contaba', 'contábamos', 'contabais', 'contaban'],
    futuro: ['contaré', 'contarás', 'contará', 'contaremos', 'contaréis', 'contarán'],
    condicional: ['contaría', 'contarías', 'contaría', 'contaríamos', 'contaríais', 'contarían'],
    subjPresente: ['cuente', 'cuentes', 'cuente', 'contemos', 'contéis', 'cuenten'],
    imperativoAfirmativo: [null, 'cuenta', 'cuente', 'contemos', 'contad', 'cuenten'],
    imperativoNegativo: [null, 'no cuentes', 'no cuente', 'no contemos', 'no contéis', 'no cuenten'],
    gerundio: 'contando', participio: 'contado',
  },
  encontrar: {
    presente: ['encuentro', 'encuentras', 'encuentra', 'encontramos', 'encontráis', 'encuentran'],
    preterito: ['encontré', 'encontraste', 'encontró', 'encontramos', 'encontrasteis', 'encontraron'],
    imperfecto: ['encontraba', 'encontrabas', 'encontraba', 'encontrábamos', 'encontrabais', 'encontraban'],
    futuro: ['encontraré', 'encontrarás', 'encontrará', 'encontraremos', 'encontraréis', 'encontrarán'],
    condicional: ['encontraría', 'encontrarías', 'encontraría', 'encontraríamos', 'encontraríais', 'encontrarían'],
    subjPresente: ['encuentre', 'encuentres', 'encuentre', 'encontremos', 'encontréis', 'encuentren'],
    imperativoAfirmativo: [null, 'encuentra', 'encuentre', 'encontremos', 'encontrad', 'encuentren'],
    imperativoNegativo: [null, 'no encuentres', 'no encuentre', 'no encontremos', 'no encontréis', 'no encuentren'],
    gerundio: 'encontrando', participio: 'encontrado',
  },
  probar: {
    presente: ['pruebo', 'pruebas', 'prueba', 'probamos', 'probáis', 'prueban'],
    preterito: ['probé', 'probaste', 'probó', 'probamos', 'probasteis', 'probaron'],
    imperfecto: ['probaba', 'probabas', 'probaba', 'probábamos', 'probabais', 'probaban'],
    futuro: ['probaré', 'probarás', 'probará', 'probaremos', 'probaréis', 'probarán'],
    condicional: ['probaría', 'probarías', 'probaría', 'probaríamos', 'probaríais', 'probarían'],
    subjPresente: ['pruebe', 'pruebes', 'pruebe', 'probemos', 'probéis', 'prueben'],
    imperativoAfirmativo: [null, 'prueba', 'pruebe', 'probemos', 'probad', 'prueben'],
    imperativoNegativo: [null, 'no pruebes', 'no pruebe', 'no probemos', 'no probéis', 'no prueben'],
    gerundio: 'probando', participio: 'probado',
  },
  volcar: {
    presente: ['vuelco', 'vuelcas', 'vuelca', 'volcamos', 'volcáis', 'vuelcan'],
    preterito: ['volqué', 'volcaste', 'volcó', 'volcamos', 'volcasteis', 'volcaron'],
    imperfecto: ['volcaba', 'volcabas', 'volcaba', 'volcábamos', 'volcabais', 'volcaban'],
    futuro: ['volcaré', 'volcarás', 'volcará', 'volcaremos', 'volcaréis', 'volcarán'],
    condicional: ['volcaría', 'volcarías', 'volcaría', 'volcaríamos', 'volcaríais', 'volcarían'],
    subjPresente: ['vuelque', 'vuelques', 'vuelque', 'volquemos', 'volquéis', 'vuelquen'],
    imperativoAfirmativo: [null, 'vuelca', 'vuelque', 'volquemos', 'volcad', 'vuelquen'],
    imperativoNegativo: [null, 'no vuelques', 'no vuelque', 'no volquemos', 'no volquéis', 'no vuelquen'],
    gerundio: 'volcando', participio: 'volcado',
  },
  dormir: {
    presente: ['duermo', 'duermes', 'duerme', 'dormimos', 'dormís', 'duermen'],
    preterito: ['dormí', 'dormiste', 'durmió', 'dormimos', 'dormisteis', 'durmieron'],
    imperfecto: ['dormía', 'dormías', 'dormía', 'dormíamos', 'dormíais', 'dormían'],
    futuro: ['dormiré', 'dormirás', 'dormirá', 'dormiremos', 'dormiréis', 'dormirán'],
    condicional: ['dormiría', 'dormirías', 'dormiría', 'dormiríamos', 'dormiríais', 'dormirían'],
    subjPresente: ['duerma', 'duermas', 'duerma', 'durmamos', 'durmáis', 'duerman'],
    imperativoAfirmativo: [null, 'duerme', 'duerma', 'durmamos', 'dormid', 'duerman'],
    imperativoNegativo: [null, 'no duermas', 'no duerma', 'no durmamos', 'no durmáis', 'no duerman'],
    gerundio: 'durmiendo', participio: 'dormido',
  },
  morir: {
    presente: ['muero', 'mueres', 'muere', 'morimos', 'morís', 'mueren'],
    preterito: ['morí', 'moriste', 'murió', 'morimos', 'moristeis', 'murieron'],
    imperfecto: ['moría', 'morías', 'moría', 'moríamos', 'moríais', 'morían'],
    futuro: ['moriré', 'morirás', 'morirá', 'moriremos', 'moriréis', 'morirán'],
    condicional: ['moriría', 'morirías', 'moriría', 'moriríamos', 'moriríais', 'morirían'],
    subjPresente: ['muera', 'mueras', 'muera', 'muramos', 'muráis', 'mueran'],
    imperativoAfirmativo: [null, 'muere', 'muera', 'muramos', 'morid', 'mueran'],
    imperativoNegativo: [null, 'no mueras', 'no muera', 'no muramos', 'no muráis', 'no mueran'],
    gerundio: 'muriendo', participio: 'muerto',
  },
  pedir: {
    presente: ['pido', 'pides', 'pide', 'pedimos', 'pedís', 'piden'],
    preterito: ['pedí', 'pediste', 'pidió', 'pedimos', 'pedisteis', 'pidieron'],
    imperfecto: ['pedía', 'pedías', 'pedía', 'pedíamos', 'pedíais', 'pedían'],
    futuro: ['pediré', 'pedirás', 'pedirá', 'pediremos', 'pediréis', 'pedirán'],
    condicional: ['pediría', 'pedirías', 'pediría', 'pediríamos', 'pediríais', 'pedirían'],
    subjPresente: ['pida', 'pidas', 'pida', 'pidamos', 'pidáis', 'pidan'],
    imperativoAfirmativo: [null, 'pide', 'pida', 'pidamos', 'pedid', 'pidan'],
    imperativoNegativo: [null, 'no pidas', 'no pida', 'no pidamos', 'no pidáis', 'no pidan'],
    gerundio: 'pidiendo', participio: 'pedido',
  },
  despedir: {
    presente: ['despido', 'despides', 'despide', 'despedimos', 'despedís', 'despiden'],
    preterito: ['despedí', 'despediste', 'despidió', 'despedimos', 'despedisteis', 'despidieron'],
    imperfecto: ['despedía', 'despedías', 'despedía', 'despedíamos', 'despedíais', 'despedían'],
    futuro: ['despediré', 'despedirás', 'despedirá', 'despediremos', 'despediréis', 'despedirán'],
    condicional: ['despediría', 'despedirías', 'despediría', 'despediríamos', 'despediríais', 'despedirían'],
    subjPresente: ['despida', 'despidas', 'despida', 'despidamos', 'despidáis', 'despidan'],
    imperativoAfirmativo: [null, 'despide', 'despida', 'despidamos', 'despedid', 'despidan'],
    imperativoNegativo: [null, 'no despidas', 'no despida', 'no despidamos', 'no despidáis', 'no despidan'],
    gerundio: 'despidiendo', participio: 'despedido',
  },
  repetir: {
    presente: ['repito', 'repites', 'repite', 'repetimos', 'repetís', 'repiten'],
    preterito: ['repetí', 'repetiste', 'repitió', 'repetimos', 'repetisteis', 'repitieron'],
    imperfecto: ['repetía', 'repetías', 'repetía', 'repetíamos', 'repetíais', 'repetían'],
    futuro: ['repetiré', 'repetirás', 'repetirá', 'repetiremos', 'repetiréis', 'repetirán'],
    condicional: ['repetiría', 'repetirías', 'repetiría', 'repetiríamos', 'repetiríais', 'repetirían'],
    subjPresente: ['repita', 'repitas', 'repita', 'repitamos', 'repitáis', 'repitan'],
    imperativoAfirmativo: [null, 'repite', 'repita', 'repitamos', 'repetid', 'repitan'],
    imperativoNegativo: [null, 'no repitas', 'no repita', 'no repitamos', 'no repitáis', 'no repitan'],
    gerundio: 'repitiendo', participio: 'repetido',
  },
  servir: {
    presente: ['sirvo', 'sirves', 'sirve', 'servimos', 'servís', 'sirven'],
    preterito: ['serví', 'serviste', 'sirvió', 'servimos', 'servisteis', 'sirvieron'],
    imperfecto: ['servía', 'servías', 'servía', 'servíamos', 'servíais', 'servían'],
    futuro: ['serviré', 'servirás', 'servirá', 'serviremos', 'serviréis', 'servirán'],
    condicional: ['serviría', 'servirías', 'serviría', 'serviríamos', 'serviríais', 'servirían'],
    subjPresente: ['sirva', 'sirvas', 'sirva', 'sirvamos', 'sirváis', 'sirvan'],
    imperativoAfirmativo: [null, 'sirve', 'sirva', 'sirvamos', 'servid', 'sirvan'],
    imperativoNegativo: [null, 'no sirvas', 'no sirva', 'no sirvamos', 'no sirváis', 'no sirvan'],
    gerundio: 'sirviendo', participio: 'servido',
  },
  jugar: {
    presente: ['juego', 'juegas', 'juega', 'jugamos', 'jugáis', 'juegan'],
    preterito: ['jugué', 'jugaste', 'jugó', 'jugamos', 'jugasteis', 'jugaron'],
    imperfecto: ['jugaba', 'jugabas', 'jugaba', 'jugábamos', 'jugabais', 'jugaban'],
    futuro: ['jugaré', 'jugarás', 'jugará', 'jugaremos', 'jugaréis', 'jugarán'],
    condicional: ['jugaría', 'jugarías', 'jugaría', 'jugaríamos', 'jugaríais', 'jugarían'],
    subjPresente: ['juegue', 'juegues', 'juegue', 'juguemos', 'juguéis', 'jueguen'],
    imperativoAfirmativo: [null, 'juega', 'juegue', 'juguemos', 'jugad', 'jueguen'],
    imperativoNegativo: [null, 'no juegues', 'no juegue', 'no juguemos', 'no juguéis', 'no jueguen'],
    gerundio: 'jugando', participio: 'jugado',
  },
  vaciar: {
    presente: ['vacío', 'vacías', 'vacía', 'vaciamos', 'vaciáis', 'vacían'],
    preterito: ['vacié', 'vaciaste', 'vació', 'vaciamos', 'vaciasteis', 'vaciaron'],
    imperfecto: ['vaciaba', 'vaciabas', 'vaciaba', 'vaciábamos', 'vaciabais', 'vaciaban'],
    futuro: ['vaciaré', 'vaciarás', 'vaciará', 'vaciaremos', 'vaciaréis', 'vaciarán'],
    condicional: ['vaciaría', 'vaciarías', 'vaciaría', 'vaciaríamos', 'vaciaríais', 'vaciarían'],
    subjPresente: ['vacíe', 'vacíes', 'vacíe', 'vaciemos', 'vaciéis', 'vacíen'],
    imperativoAfirmativo: [null, 'vacía', 'vacíe', 'vaciemos', 'vaciad', 'vacíen'],
    imperativoNegativo: [null, 'no vacíes', 'no vacíe', 'no vaciemos', 'no vaciéis', 'no vacíen'],
    gerundio: 'vaciando', participio: 'vaciado',
  },
  reunir: {
    presente: ['reúno', 'reúnes', 'reúne', 'reunimos', 'reunís', 'reúnen'],
    preterito: ['reuní', 'reuniste', 'reunió', 'reunimos', 'reunisteis', 'reunieron'],
    imperfecto: ['reunía', 'reunías', 'reunía', 'reuníamos', 'reuníais', 'reunían'],
    futuro: ['reuniré', 'reunirás', 'reunirá', 'reuniremos', 'reuniréis', 'reunirán'],
    condicional: ['reuniría', 'reunirías', 'reuniría', 'reuniríamos', 'reuniríais', 'reunirían'],
    subjPresente: ['reúna', 'reúnas', 'reúna', 'reunamos', 'reunáis', 'reúnan'],
    imperativoAfirmativo: [null, 'reúne', 'reúna', 'reunamos', 'reunid', 'reúnan'],
    imperativoNegativo: [null, 'no reúnas', 'no reúna', 'no reunamos', 'no reunáis', 'no reúnan'],
    gerundio: 'reuniendo', participio: 'reunido',
  },
  sentar: {
    presente: ['siento', 'sientas', 'sienta', 'sentamos', 'sentáis', 'sientan'],
    preterito: ['senté', 'sentaste', 'sentó', 'sentamos', 'sentasteis', 'sentaron'],
    imperfecto: ['sentaba', 'sentabas', 'sentaba', 'sentábamos', 'sentabais', 'sentaban'],
    futuro: ['sentaré', 'sentarás', 'sentará', 'sentaremos', 'sentaréis', 'sentarán'],
    condicional: ['sentaría', 'sentarías', 'sentaría', 'sentaríamos', 'sentaríais', 'sentarían'],
    subjPresente: ['siente', 'sientes', 'siente', 'sentemos', 'sentéis', 'sienten'],
    imperativoAfirmativo: [null, 'sienta', 'siente', 'sentemos', 'sentad', 'sienten'],
    imperativoNegativo: [null, 'no sientes', 'no siente', 'no sentemos', 'no sentéis', 'no sienten'],
    gerundio: 'sentando', participio: 'sentado',
  },
  despertar: {
    presente: ['despierto', 'despiertas', 'despierta', 'despertamos', 'despertáis', 'despiertan'],
    preterito: ['desperté', 'despertaste', 'despertó', 'despertamos', 'despertasteis', 'despertaron'],
    imperfecto: ['despertaba', 'despertabas', 'despertaba', 'despertábamos', 'despertabais', 'despertaban'],
    futuro: ['despertaré', 'despertarás', 'despertará', 'despertaremos', 'despertaréis', 'despertarán'],
    condicional: ['despertaría', 'despertarías', 'despertaría', 'despertaríamos', 'despertaríais', 'despertarían'],
    subjPresente: ['despierte', 'despiertes', 'despierte', 'despertemos', 'despertéis', 'despierten'],
    imperativoAfirmativo: [null, 'despierta', 'despierte', 'despertemos', 'despertad', 'despierten'],
    imperativoNegativo: [null, 'no despiertes', 'no despierte', 'no despertemos', 'no despertéis', 'no despierten'],
    gerundio: 'despertando', participio: 'despertado',
  },
  encender: {
    presente: ['enciendo', 'enciendes', 'enciende', 'encendemos', 'encendéis', 'encienden'],
    preterito: ['encendí', 'encendiste', 'encendió', 'encendimos', 'encendisteis', 'encendieron'],
    imperfecto: ['encendía', 'encendías', 'encendía', 'encendíamos', 'encendíais', 'encendían'],
    futuro: ['encenderé', 'encenderás', 'encenderá', 'encenderemos', 'encenderéis', 'encenderán'],
    condicional: ['encendería', 'encenderías', 'encendería', 'encenderíamos', 'encenderíais', 'encenderían'],
    subjPresente: ['encienda', 'enciendas', 'encienda', 'encendamos', 'encendáis', 'enciendan'],
    imperativoAfirmativo: [null, 'enciende', 'encienda', 'encendamos', 'encended', 'enciendan'],
    imperativoNegativo: [null, 'no enciendas', 'no encienda', 'no encendamos', 'no encendáis', 'no enciendan'],
    gerundio: 'encendiendo', participio: 'encendido',
  },
  mentir: {
    presente: ['miento', 'mientes', 'miente', 'mentimos', 'mentís', 'mienten'],
    preterito: ['mentí', 'mentiste', 'mintió', 'mentimos', 'mentisteis', 'mintieron'],
    imperfecto: ['mentía', 'mentías', 'mentía', 'mentíamos', 'mentíais', 'mentían'],
    futuro: ['mentiré', 'mentirás', 'mentirá', 'mentiremos', 'mentiréis', 'mentirán'],
    condicional: ['mentiría', 'mentirías', 'mentiría', 'mentiríamos', 'mentiríais', 'mentirían'],
    subjPresente: ['mienta', 'mientas', 'mienta', 'mintamos', 'mintáis', 'mientan'],
    imperativoAfirmativo: [null, 'miente', 'mienta', 'mintamos', 'mentid', 'mientan'],
    imperativoNegativo: [null, 'no mientas', 'no mienta', 'no mintamos', 'no mintáis', 'no mientan'],
    gerundio: 'mintiendo', participio: 'mentido',
  },
  acostar: {
    presente: ['acuesto', 'acuestas', 'acuesta', 'acostamos', 'acostáis', 'acuestan'],
    preterito: ['acosté', 'acostaste', 'acostó', 'acostamos', 'acostasteis', 'acostaron'],
    imperfecto: ['acostaba', 'acostabas', 'acostaba', 'acostábamos', 'acostabais', 'acostaban'],
    futuro: ['acostaré', 'acostarás', 'acostará', 'acostaremos', 'acostaréis', 'acostarán'],
    condicional: ['acostaría', 'acostarías', 'acostaría', 'acostaríamos', 'acostaríais', 'acostarían'],
    subjPresente: ['acueste', 'acuestes', 'acueste', 'acostemos', 'acostéis', 'acuesten'],
    imperativoAfirmativo: [null, 'acuesta', 'acueste', 'acostemos', 'acostad', 'acuesten'],
    imperativoNegativo: [null, 'no acuestes', 'no acueste', 'no acostemos', 'no acostéis', 'no acuesten'],
    gerundio: 'acostando', participio: 'acostado',
  },
  mostrar: {
    presente: ['muestro', 'muestras', 'muestra', 'mostramos', 'mostráis', 'muestran'],
    preterito: ['mostré', 'mostraste', 'mostró', 'mostramos', 'mostrasteis', 'mostraron'],
    imperfecto: ['mostraba', 'mostrabas', 'mostraba', 'mostrábamos', 'mostrabais', 'mostraban'],
    futuro: ['mostraré', 'mostrarás', 'mostrará', 'mostraremos', 'mostraréis', 'mostrarán'],
    condicional: ['mostraría', 'mostrarías', 'mostraría', 'mostraríamos', 'mostraríais', 'mostrarían'],
    subjPresente: ['muestre', 'muestres', 'muestre', 'mostremos', 'mostréis', 'muestren'],
    imperativoAfirmativo: [null, 'muestra', 'muestre', 'mostremos', 'mostrad', 'muestren'],
    imperativoNegativo: [null, 'no muestres', 'no muestre', 'no mostremos', 'no mostréis', 'no muestren'],
    gerundio: 'mostrando', participio: 'mostrado',
  },
  recordar: {
    presente: ['recuerdo', 'recuerdas', 'recuerda', 'recordamos', 'recordáis', 'recuerdan'],
    preterito: ['recordé', 'recordaste', 'recordó', 'recordamos', 'recordasteis', 'recordaron'],
    imperfecto: ['recordaba', 'recordabas', 'recordaba', 'recordábamos', 'recordabais', 'recordaban'],
    futuro: ['recordaré', 'recordarás', 'recordará', 'recordaremos', 'recordaréis', 'recordarán'],
    condicional: ['recordaría', 'recordarías', 'recordaría', 'recordaríamos', 'recordaríais', 'recordarían'],
    subjPresente: ['recuerde', 'recuerdes', 'recuerde', 'recordemos', 'recordéis', 'recuerden'],
    imperativoAfirmativo: [null, 'recuerda', 'recuerde', 'recordemos', 'recordad', 'recuerden'],
    imperativoNegativo: [null, 'no recuerdes', 'no recuerde', 'no recordemos', 'no recordéis', 'no recuerden'],
    gerundio: 'recordando', participio: 'recordado',
  },
  costar: {
    presente: ['cuesto', 'cuestas', 'cuesta', 'costamos', 'costáis', 'cuestan'],
    preterito: ['costé', 'costaste', 'costó', 'costamos', 'costasteis', 'costaron'],
    imperfecto: ['costaba', 'costabas', 'costaba', 'costábamos', 'costabais', 'costaban'],
    futuro: ['costaré', 'costarás', 'costará', 'costaremos', 'costaréis', 'costarán'],
    condicional: ['costaría', 'costarías', 'costaría', 'costaríamos', 'costaríais', 'costarían'],
    subjPresente: ['cueste', 'cuestes', 'cueste', 'costemos', 'costéis', 'cuesten'],
    imperativoAfirmativo: [null, 'cuesta', 'cueste', 'costemos', 'costad', 'cuesten'],
    imperativoNegativo: [null, 'no cuestes', 'no cueste', 'no costemos', 'no costéis', 'no cuesten'],
    gerundio: 'costando', participio: 'costado',
  },
  'soñar': {
    presente: ['sueño', 'sueñas', 'sueña', 'soñamos', 'soñáis', 'sueñan'],
    preterito: ['soñé', 'soñaste', 'soñó', 'soñamos', 'soñasteis', 'soñaron'],
    imperfecto: ['soñaba', 'soñabas', 'soñaba', 'soñábamos', 'soñabais', 'soñaban'],
    futuro: ['soñaré', 'soñarás', 'soñará', 'soñaremos', 'soñaréis', 'soñarán'],
    condicional: ['soñaría', 'soñarías', 'soñaría', 'soñaríamos', 'soñaríais', 'soñarían'],
    subjPresente: ['sueñe', 'sueñes', 'sueñe', 'soñemos', 'soñéis', 'sueñen'],
    imperativoAfirmativo: [null, 'sueña', 'sueñe', 'soñemos', 'soñad', 'sueñen'],
    imperativoNegativo: [null, 'no sueñes', 'no sueñe', 'no soñemos', 'no soñéis', 'no sueñen'],
    gerundio: 'soñando', participio: 'soñado',
  },
  almorzar: {
    presente: ['almuerzo', 'almuerzas', 'almuerza', 'almorzamos', 'almorzáis', 'almuerzan'],
    preterito: ['almorcé', 'almorzaste', 'almorzó', 'almorzamos', 'almorzasteis', 'almorzaron'],
    imperfecto: ['almorzaba', 'almorzabas', 'almorzaba', 'almorzábamos', 'almorzabais', 'almorzaban'],
    futuro: ['almorzaré', 'almorzarás', 'almorzará', 'almorzaremos', 'almorzaréis', 'almorzarán'],
    condicional: ['almorzaría', 'almorzarías', 'almorzaría', 'almorzaríamos', 'almorzaríais', 'almorzarían'],
    subjPresente: ['almuerce', 'almuerces', 'almuerce', 'almorcemos', 'almorcéis', 'almuercen'],
    imperativoAfirmativo: [null, 'almuerza', 'almuerce', 'almorcemos', 'almorzad', 'almuercen'],
    imperativoNegativo: [null, 'no almuerces', 'no almuerce', 'no almorcemos', 'no almorcéis', 'no almuercen'],
    gerundio: 'almorzando', participio: 'almorzado',
  },
  mover: {
    presente: ['muevo', 'mueves', 'mueve', 'movemos', 'movéis', 'mueven'],
    preterito: ['moví', 'moviste', 'movió', 'movimos', 'movisteis', 'movieron'],
    imperfecto: ['movía', 'movías', 'movía', 'movíamos', 'movíais', 'movían'],
    futuro: ['moveré', 'moverás', 'moverá', 'moveremos', 'moveréis', 'moverán'],
    condicional: ['movería', 'moverías', 'movería', 'moveríamos', 'moveríais', 'moverían'],
    subjPresente: ['mueva', 'muevas', 'mueva', 'movamos', 'mováis', 'muevan'],
    imperativoAfirmativo: [null, 'mueve', 'mueva', 'movamos', 'moved', 'muevan'],
    imperativoNegativo: [null, 'no muevas', 'no mueva', 'no movamos', 'no mováis', 'no muevan'],
    gerundio: 'moviendo', participio: 'movido',
  },
  doler: {
    presente: ['duelo', 'dueles', 'duele', 'dolemos', 'doléis', 'duelen'],
    preterito: ['dolí', 'doliste', 'dolió', 'dolimos', 'dolisteis', 'dolieron'],
    imperfecto: ['dolía', 'dolías', 'dolía', 'dolíamos', 'dolíais', 'dolían'],
    futuro: ['doleré', 'dolerás', 'dolerá', 'doleremos', 'doleréis', 'dolerán'],
    condicional: ['dolería', 'dolerías', 'dolería', 'doleríamos', 'doleríais', 'dolerían'],
    subjPresente: ['duela', 'duelas', 'duela', 'dolamos', 'doláis', 'duelan'],
    imperativoAfirmativo: [null, 'duele', 'duela', 'dolamos', 'doled', 'duelan'],
    imperativoNegativo: [null, 'no duelas', 'no duela', 'no dolamos', 'no doláis', 'no duelan'],
    gerundio: 'doliendo', participio: 'dolido',
  },
  vestir: {
    presente: ['visto', 'vistes', 'viste', 'vestimos', 'vestís', 'visten'],
    preterito: ['vestí', 'vestiste', 'vistió', 'vestimos', 'vestisteis', 'vistieron'],
    imperfecto: ['vestía', 'vestías', 'vestía', 'vestíamos', 'vestíais', 'vestían'],
    futuro: ['vestiré', 'vestirás', 'vestirá', 'vestiremos', 'vestiréis', 'vestirán'],
    condicional: ['vestiría', 'vestirías', 'vestiría', 'vestiríamos', 'vestiríais', 'vestirían'],
    subjPresente: ['vista', 'vistas', 'vista', 'vistamos', 'vistáis', 'vistan'],
    imperativoAfirmativo: [null, 'viste', 'vista', 'vistamos', 'vestid', 'vistan'],
    imperativoNegativo: [null, 'no vistas', 'no vista', 'no vistamos', 'no vistáis', 'no vistan'],
    gerundio: 'vistiendo', participio: 'vestido',
  },
  seguir: {
    presente: ['sigo', 'sigues', 'sigue', 'seguimos', 'seguís', 'siguen'],
    preterito: ['seguí', 'seguiste', 'siguió', 'seguimos', 'seguisteis', 'siguieron'],
    imperfecto: ['seguía', 'seguías', 'seguía', 'seguíamos', 'seguíais', 'seguían'],
    futuro: ['seguiré', 'seguirás', 'seguirá', 'seguiremos', 'seguiréis', 'seguirán'],
    condicional: ['seguiría', 'seguirías', 'seguiría', 'seguiríamos', 'seguiríais', 'seguirían'],
    subjPresente: ['siga', 'sigas', 'siga', 'sigamos', 'sigáis', 'sigan'],
    imperativoAfirmativo: [null, 'sigue', 'siga', 'sigamos', 'seguid', 'sigan'],
    imperativoNegativo: [null, 'no sigas', 'no siga', 'no sigamos', 'no sigáis', 'no sigan'],
    gerundio: 'siguiendo', participio: 'seguido',
  },
  conseguir: {
    presente: ['consigo', 'consigues', 'consigue', 'conseguimos', 'conseguís', 'consiguen'],
    preterito: ['conseguí', 'conseguiste', 'consiguió', 'conseguimos', 'conseguisteis', 'consiguieron'],
    imperfecto: ['conseguía', 'conseguías', 'conseguía', 'conseguíamos', 'conseguíais', 'conseguían'],
    futuro: ['conseguiré', 'conseguirás', 'conseguirá', 'conseguiremos', 'conseguiréis', 'conseguirán'],
    condicional: ['conseguiría', 'conseguirías', 'conseguiría', 'conseguiríamos', 'conseguiríais', 'conseguirían'],
    subjPresente: ['consiga', 'consigas', 'consiga', 'consigamos', 'consigáis', 'consigan'],
    imperativoAfirmativo: [null, 'consigue', 'consiga', 'consigamos', 'conseguid', 'consigan'],
    imperativoNegativo: [null, 'no consigas', 'no consiga', 'no consigamos', 'no consigáis', 'no consigan'],
    gerundio: 'consiguiendo', participio: 'conseguido',
  },
}
