// Script guard for LLM-sourced discovery words (A2). Discovery vocabulary is generated by the model
// and persisted WITHOUT the spellcheck gate that the manual add flow applies (checkSpelling lives in
// app/api/words/enrich only). The observed failure mode is not misspelling but SCRIPT CONTAMINATION —
// e.g. "bebер", where the trailing "ер" are Cyrillic homoglyphs (U+0435 U+0440) of Latin "er", which
// slugified to "beb" and mis-synthesized. A dictionary check is the wrong tool (valid Spanish words
// like "bachata"/"kilombo" are legitimately absent from Hunspell), so we guard on script instead:
// allow Latin letters, combining accent marks, and word-internal spacing/joining punctuation only.
//
// Precomposed accented Spanish letters (á é í ó ú ñ ü) are themselves \p{Script=Latin}; \p{M} covers
// any decomposed (NFD) accents. Space admits multi-word phrases ("a menudo"); hyphen/apostrophe admit
// compounds. Anything containing a non-Latin letter (Cyrillic, Greek, CJK, …) fails.
const LATIN_ONLY = /^[\p{Script=Latin}\p{M}\s'’-]+$/u

export function isLatinScript(word: string): boolean {
  return LATIN_ONLY.test(word.trim())
}
