// Discovery-pool seed generator + verifier. Captures the live `discovery_pool` corpus (seeded via
// hand-authored SQL, no backing commit) as a committed, replayable migration.
//
// Usage:
//   npx tsx scripts/dump-discovery-pool.ts           # verify + report ONLY (writes nothing)
//   npx tsx scripts/dump-discovery-pool.ts --emit     # after approval: also write the .sql migration
//
// Env: reads NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (service-role bypasses RLS). This is a
// tsx script — never imported into the client bundle, so it is server-only by construction (mirrors
// scripts/backfill-audio.ts; does NOT import lib/supabase/admin.ts, which is `import 'server-only'`).
// No credentials are ever written to the migration or logged.

import { loadEnvConfig } from '@next/env'
import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'node:fs'
import { selectPoolCards, type DiscoveryPoolRow, type PoolBand } from '../lib/discovery-pool'
import { isLatinScript } from '../lib/latin-script'

loadEnvConfig(process.cwd())

const EMIT = process.argv.includes('--emit')
const MIGRATION_PATH = 'supabase/migrations/20260824000000_discovery_pool_seed.sql'

// Documented seeded state (PROJECT_STATE.md → "SEEDED STATE"). Reported explicitly, never asserted-away.
const EXPECTED: Record<string, number> = {
  esencial: 187,
  comida: 62,
  casa: 60,
  cuerpo: 60,
  ropa: 60,
  viaje: 63,
  trabajo: 60,
  familia: 60,
  fiesta: 60,
}
const EXPECTED_TOTAL = Object.values(EXPECTED).reduce((a, b) => a + b, 0)

const url = process.env.NEXT_PUBLIC_SUPABASE_URL
const key = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}
const supabase = createClient(url, key)

// The semantic columns we read + dump (id/created_at omitted from the dump; read here only for count).
type PoolRow = {
  id: string
  theme_key: string
  word: string
  fr: string
  pos: string
  gender: 'm' | 'f' | null
  example: unknown
  band: string
  fill_source: string
  status: string
}

const SELECT_COLS = 'id, theme_key, word, fr, pos, gender, example, band, fill_source, status'

function validExample(ex: unknown): ex is { es: string; fr: string } {
  if (typeof ex !== 'object' || ex === null) return false
  const o = ex as Record<string, unknown>
  return typeof o.es === 'string' && o.es.trim() !== '' && typeof o.fr === 'string' && o.fr.trim() !== ''
}

// Map a DB row into the read-path's DiscoveryPoolRow so the draw test uses the REAL selectPoolCards.
function toPoolRow(r: PoolRow): DiscoveryPoolRow {
  const band: PoolBand = r.band === 'extended' ? 'extended' : 'core'
  return {
    id: r.id,
    word: r.word,
    fr: r.fr,
    pos: r.pos,
    gender: r.gender === 'm' || r.gender === 'f' ? r.gender : null,
    example: validExample(r.example) ? r.example : { es: '', fr: '' },
    band,
    status: r.status === 'flagged' ? 'flagged' : 'active',
  }
}

// ── SQL emitters (only used on --emit) ──────────────────────────────────────
// standard_conforming_strings is on by default → backslashes are literal; only single quotes need doubling.
function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}
function sqlGender(g: 'm' | 'f' | null): string {
  return g === null ? 'NULL' : sqlStr(g)
}
function sqlJson(ex: unknown): string {
  return `${sqlStr(JSON.stringify(ex))}::jsonb`
}

function emitThemeInsert(theme: string, rows: PoolRow[]): string {
  const ordered = [...rows].sort((a, b) => {
    const x = a.word.toLowerCase()
    const y = b.word.toLowerCase()
    return x < y ? -1 : x > y ? 1 : 0
  })
  const values = ordered
    .map(
      (r) =>
        `  (${sqlStr(r.theme_key)}, ${sqlStr(r.word)}, ${sqlStr(r.fr)}, ${sqlStr(r.pos)}, ` +
        `${sqlGender(r.gender)}, ${sqlJson(r.example)}, ${sqlStr(r.band)}, ${sqlStr(r.fill_source)}, ${sqlStr(r.status)})`,
    )
    .join(',\n')
  return (
    `-- ${theme} (${ordered.length})\n` +
    `INSERT INTO discovery_pool (theme_key, word, fr, pos, gender, example, band, fill_source, status) VALUES\n` +
    `${values}\n` +
    `ON CONFLICT (theme_key, lower(word)) DO NOTHING;\n`
  )
}

function buildMigration(rows: PoolRow[], themeCounts: Map<string, number>): string {
  const themes = [...themeCounts.keys()].sort()
  const header =
    `-- Discovery pool seed (DATA ONLY) — captures the live discovery_pool corpus as a committed,\n` +
    `-- replayable artifact. Generated by scripts/dump-discovery-pool.ts from live Supabase (2026-08-24).\n` +
    `-- No schema change: the table exists from 20260717000000_discovery_pool.sql. Idempotent —\n` +
    `-- ON CONFLICT (theme_key, lower(word)) DO NOTHING mirrors the unique index discovery_pool_theme_word_idx,\n` +
    `-- so replaying on an already-seeded DB (incl. current live) is a safe no-op. id + created_at omitted\n` +
    `-- (defaults; nothing FKs discovery_pool.id — discovery copies by value into words). No credentials here.\n\n`
  const body = themes.map((t) => emitThemeInsert(t, rows.filter((r) => r.theme_key === t))).join('\n')
  const countLines = themes.map((t) => `--   ${t}: ${themeCounts.get(t)}`).join('\n')
  const footer = `\n-- Total: ${rows.length} rows\n${countLines}\n`
  return header + body + footer
}

async function main(): Promise<void> {
  console.log(EMIT ? '=== dump-discovery-pool --emit ===' : '=== dump-discovery-pool (VERIFY ONLY — writes nothing) ===\n')

  const { data, error, count } = await supabase
    .from('discovery_pool')
    .select(SELECT_COLS, { count: 'exact' })
    .range(0, 9999)
  if (error || !data) {
    console.error('Fetch failed:', error?.message)
    process.exit(1)
  }
  const rows = data as PoolRow[]

  // Truncation guard: the exact head count must equal what we actually pulled.
  if (count !== null && count !== rows.length) {
    console.error(`⚠️  TRUNCATION: server count=${count} but fetched=${rows.length} — aborting.`)
    process.exit(1)
  }

  // ── 1. Per-theme counts vs documented seeded state ──────────────────────
  const themeCounts = new Map<string, number>()
  for (const r of rows) themeCounts.set(r.theme_key, (themeCounts.get(r.theme_key) ?? 0) + 1)

  console.log('Per-theme counts (live | expected):')
  let countsOk = true
  for (const theme of Object.keys(EXPECTED)) {
    const live = themeCounts.get(theme) ?? 0
    const exp = EXPECTED[theme]
    const ok = live === exp
    if (!ok) countsOk = false
    console.log(`  ${theme.padEnd(9)} ${String(live).padStart(3)} | ${String(exp).padStart(3)}  ${ok ? 'OK' : 'FLAG ⚠️'}`)
  }
  const unexpectedThemes = [...themeCounts.keys()].filter((t) => !(t in EXPECTED))
  for (const t of unexpectedThemes) {
    countsOk = false
    console.log(`  ${t.padEnd(9)} ${String(themeCounts.get(t)).padStart(3)} | (unexpected theme_key) FLAG ⚠️`)
  }
  console.log(`  ${'TOTAL'.padEnd(9)} ${String(rows.length).padStart(3)} | ${String(EXPECTED_TOTAL).padStart(3)}  ${rows.length === EXPECTED_TOTAL ? 'OK' : 'FLAG ⚠️'}\n`)

  // ── 2. Draw actually works (real read path) ─────────────────────────────
  console.log('Draw test — selectPoolCards per theme (excludeWords=[], limit=50):')
  let drawOk = true
  for (const theme of Object.keys(EXPECTED)) {
    const themeRows = rows.filter((r) => r.theme_key === theme).map(toPoolRow)
    const { cards } = selectPoolCards({ rows: themeRows, excludeWords: [], limit: 50 })
    const ok = cards.length > 0
    if (!ok) drawOk = false
    console.log(`  ${theme.padEnd(9)} drew ${String(cards.length).padStart(3)}  ${ok ? 'OK' : 'EMPTY ⚠️'}`)
  }
  console.log('')

  // ── 3. Field integrity over ALL rows ────────────────────────────────────
  const violations: string[] = []
  let flaggedCount = 0
  for (const r of rows) {
    if (r.status === 'flagged') flaggedCount++ // informational, NOT a violation
    const problems: string[] = []
    if (!validExample(r.example)) problems.push('example not {es,fr} non-empty')
    if (typeof r.fr !== 'string' || r.fr.trim() === '') problems.push('fr empty')
    if (typeof r.pos !== 'string' || r.pos.trim() === '') problems.push('pos empty')
    if (r.band !== 'core' && r.band !== 'extended') problems.push(`band='${r.band}'`)
    if (!(r.gender === 'm' || r.gender === 'f' || r.gender === null)) problems.push(`gender='${r.gender}'`)
    if (r.status !== 'active' && r.status !== 'flagged') problems.push(`status='${r.status}'`) // unexpected only
    if (!isLatinScript(r.word)) problems.push('non-Latin word')
    if (problems.length > 0) violations.push(`  ${r.theme_key} · ${JSON.stringify(r.word)} → ${problems.join('; ')}`)
  }

  console.log(`Field integrity (all ${rows.length} rows):`)
  console.log(`  status='flagged' (informational, dumped faithfully): ${flaggedCount}`)
  if (violations.length === 0) {
    console.log('  no malformed rows ✓\n')
  } else {
    console.log(`  ${violations.length} malformed row(s):`)
    for (const v of violations) console.log(v)
    console.log('')
  }

  const clean = countsOk && drawOk && violations.length === 0
  console.log(`SUMMARY: counts ${countsOk ? 'OK' : 'FLAG'} · draw ${drawOk ? 'OK' : 'FLAG'} · malformed ${violations.length} · flagged ${flaggedCount} (info)`)
  console.log(clean ? '✅ Pool is clean.\n' : '⚠️  Pool has flags — review before dumping.\n')

  if (!EMIT) {
    console.log('VERIFY-ONLY: no migration written. Re-run with --emit after approval.')
    return
  }

  // ── --emit: dump ALL rows regardless of status; preserve status as-is ───
  const sql = buildMigration(rows, themeCounts)
  const emittedRows = (sql.match(/^ {2}\(/gm) ?? []).length
  if (emittedRows !== rows.length) {
    console.error(`⚠️  emitted ${emittedRows} value tuples but read ${rows.length} — aborting write.`)
    process.exit(1)
  }
  writeFileSync(MIGRATION_PATH, sql, 'utf8')
  console.log(`Wrote ${MIGRATION_PATH} — ${emittedRows} rows (== read).`)
}

void main()
